// Package docs renders the Markdown README — a Mermaid ER diagram plus a
// model/enum reference — that every backend emits beside its generated output,
// so a GORM or SQL tree is documented the same way the Prisma tree already
// was. The rendering primitives are target-agnostic: a Naming chooses whether
// models and enums appear under their globally-qualified names (Prisma's one
// namespace per database) or their bare, schema-local names (GORM, SQL,
// where the schema or Go package already disambiguates them).
package docs

import (
	"fmt"
	"sort"
	"strings"

	"github.com/the-protobuf-project/protorm/plugin/generator/schema"
	"github.com/the-protobuf-project/protorm/plugin/generator/types"
)

// Marker is the generated-file banner prepended to every README so the output
// is clearly machine-generated and not hand-edited.
const Marker = "<!-- Code generated by protoc-gen-protorm. DO NOT EDIT. -->\n\n"

// Naming selects the display names a README renders, letting Prisma show
// globally-qualified model/enum names while schema-namespaced targets show the
// bare local names. Ref maps a ForeignKey.ReferencedModel (always the qualified
// name) to the display name used for the referenced model.
type Naming struct {
	Table func(*schema.Table) string
	Enum  func(*schema.Enum) string
	Ref   func(refModel string) string
}

// Qualified renders the globally-unique names — used by the Prisma README,
// whose models and enums share one namespace per database.
var Qualified = Naming{
	Table: func(t *schema.Table) string { return t.ModelName },
	Enum:  func(e *schema.Enum) string { return e.Name },
	Ref:   func(m string) string { return m },
}

// Local renders the bare, schema-local names — used by the GORM and SQL
// READMEs, where the schema or package already namespaces each model. Ref maps a
// qualified ReferencedModel back to the local name of the table it points at.
func Local(db *schema.Database) Naming {
	local := map[string]string{}
	for _, s := range db.Schemas {
		for _, t := range s.Tables {
			local[t.ModelName] = t.LocalName
		}
	}
	return Naming{
		Table: func(t *schema.Table) string { return t.LocalName },
		Enum:  func(e *schema.Enum) string { return e.LocalName },
		Ref: func(m string) string {
			if v, ok := local[m]; ok {
				return v
			}
			return m
		},
	}
}

// Meta frames a generated README with target-specific copy: a title, a one-line
// tagline, bullet lines describing the emitted files, and the Naming to render.
type Meta struct {
	Title   string
	Tagline string
	Outputs []string
	Naming  Naming
}

// Render assembles the full README for one database: heading, model/enum counts,
// a Mermaid ER diagram of the whole database, the target's output notes, then a
// per-schema model and enum reference. Used by the GORM and SQL targets;
// the Prisma target keeps its own per-folder tree but shares the primitives
// below.
func Render(db *schema.Database, meta Meta) string {
	var b strings.Builder
	b.WriteString(Marker)
	fmt.Fprintf(&b, "# `%s` — %s\n\n", db.Name, meta.Title)
	if meta.Tagline != "" {
		fmt.Fprintf(&b, "%s\n\n", meta.Tagline)
	}
	b.WriteString("Generated from Protobuf by protoc-gen-protorm. Source of truth is the `.proto` files — regenerate rather than editing.\n\n")

	var tables []*schema.Table
	var enums []*schema.Enum
	for _, s := range db.Schemas {
		tables = append(tables, s.Tables...)
		enums = append(enums, s.Enums...)
	}
	fmt.Fprintf(&b, "| Models | Enums |\n| ---: | ---: |\n| %d | %d |\n\n", len(tables), len(enums))

	b.WriteString(MermaidER(tables, meta.Naming))

	if len(meta.Outputs) > 0 {
		b.WriteString("## Output\n\n")
		for _, o := range meta.Outputs {
			fmt.Fprintf(&b, "- %s\n", o)
		}
		b.WriteString("\n")
	}

	for _, s := range db.Schemas {
		fmt.Fprintf(&b, "## Schema `%s`\n\n", s.Name)
		WriteModelDetail(&b, s.Tables, s.Enums, meta.Naming)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// MermaidER renders an erDiagram with PK/FK columns and crow's-foot edges.
// Models referenced but not in this set become external stub entities.
func MermaidER(tables []*schema.Table, n Naming) string {
	if len(tables) == 0 {
		return ""
	}
	defined := map[string]bool{}
	for _, t := range tables {
		defined[n.Table(t)] = true
	}

	var b strings.Builder
	b.WriteString("## Entity relationships\n\n```mermaid\nerDiagram\n    direction LR\n")

	stubs := map[string]bool{}
	sorted := append([]*schema.Table(nil), tables...)
	sort.Slice(sorted, func(i, j int) bool { return n.Table(sorted[i]) < n.Table(sorted[j]) })

	for _, t := range sorted {
		pk := map[string]bool{}
		if t.PKColumn != "" {
			pk[t.PKColumn] = true
		}
		fk := map[string]bool{}
		for _, f := range t.ForeignKeys {
			fk[f.Column] = true
			if !defined[n.Ref(f.ReferencedModel)] {
				stubs[n.Ref(f.ReferencedModel)] = true
			}
		}
		fmt.Fprintf(&b, "    %s {\n", mermaidID(n.Table(t)))
		any := false
		for _, c := range t.Columns {
			if !pk[c.Name] && !fk[c.Name] {
				continue
			}
			tag := ""
			switch {
			case pk[c.Name] && fk[c.Name]:
				tag = "PK, FK"
			case pk[c.Name]:
				tag = "PK"
			default:
				tag = "FK"
			}
			fmt.Fprintf(&b, "        %s %s %s\n", erType(c), safeIdent(c.Name), tag)
			any = true
		}
		if !any {
			b.WriteString("        string id PK\n")
		}
		b.WriteString("    }\n")
	}
	for _, name := range sortedKeys(stubs) {
		fmt.Fprintf(&b, "    %s {\n        string externalStub PK\n    }\n", mermaidID(name))
	}
	for _, t := range sorted {
		for _, f := range t.ForeignKeys {
			fmt.Fprintf(&b, "    %s }o--|| %s : \"%s\"\n",
				mermaidID(n.Table(t)), mermaidID(n.Ref(f.ReferencedModel)), f.Column)
		}
	}
	b.WriteString("```\n\n")
	return b.String()
}

// WriteModelDetail emits per-model field tables and the enum list for a group.
func WriteModelDetail(b *strings.Builder, tables []*schema.Table, enums []*schema.Enum, n Naming) {
	for _, t := range tables {
		fmt.Fprintf(b, "### `%s`", n.Table(t))
		if t.Name != "" {
			fmt.Fprintf(b, " → `%s`", t.Name)
		}
		b.WriteString("\n\n")
		if t.Comment != "" {
			fmt.Fprintf(b, "%s\n\n", escapeCell(t.Comment))
		}
		b.WriteString("| Column | Type | Null |\n| --- | --- | --- |\n")
		for _, c := range t.Columns {
			null := "not null"
			if c.Optional {
				null = "nullable"
			}
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", c.Name, columnType(c, n), null)
		}
		b.WriteString("\n")
	}
	if len(enums) > 0 {
		b.WriteString("### Enums\n\n")
		for _, e := range enums {
			vals := make([]string, len(e.Values))
			for i, v := range e.Values {
				vals[i] = v.Name
			}
			fmt.Fprintf(b, "- `%s`: %s\n", n.Enum(e), strings.Join(vals, ", "))
		}
		b.WriteString("\n")
	}
}

func columnType(c *schema.Column, n Naming) string {
	if c.Enum != nil {
		return n.Enum(c.Enum)
	}
	return c.SQLType
}

// erType maps a column to a Mermaid-safe attribute type keyword.
func erType(c *schema.Column) string {
	if c.Enum != nil {
		return "string"
	}
	base, _ := types.BaseType(c.SQLType)
	switch base {
	case "BOOLEAN", "BOOL":
		return "bool"
	case "SMALLINT", "INTEGER", "INT", "BIGINT":
		return "int"
	case "REAL", "DOUBLE PRECISION", "NUMERIC", "DECIMAL":
		return "float"
	case "TIMESTAMPTZ", "TIMESTAMP", "DATE", "TIME":
		return "datetime"
	case "JSON", "JSONB":
		return "json"
	case "BYTEA":
		return "bytes"
	default:
		return "string"
	}
}

func mermaidID(name string) string {
	id := safeIdent(name)
	if id == "" {
		return "Model"
	}
	return id
}

func safeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func escapeCell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
