// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protorm/v1/annotations.proto

package protormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protorm_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DatasourceOptions)(nil),
		Field:         50000,
		Name:          "protorm.v1.datasource",
		Tag:           "bytes,50000,opt,name=datasource",
		Filename:      "protorm/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableOptions)(nil),
		Field:         50001,
		Name:          "protorm.v1.table",
		Tag:           "bytes,50001,opt,name=table",
		Filename:      "protorm/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ColOptions)(nil),
		Field:         50002,
		Name:          "protorm.v1.col",
		Tag:           "bytes,50002,opt,name=col",
		Filename:      "protorm/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// datasource configures the database name, schema, provider, and URL.
	//
	// optional protorm.v1.DatasourceOptions datasource = 50000;
	E_Datasource = &file_protorm_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// table overrides table-level generation: table name, id strategy, timestamps, indexes.
	//
	// optional protorm.v1.TableOptions table = 50001;
	E_Table = &file_protorm_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// col overrides column-level generation: type, sizing, FK actions.
	//
	// optional protorm.v1.ColOptions col = 50002;
	E_Col = &file_protorm_v1_annotations_proto_extTypes[2]
)

var File_protorm_v1_annotations_proto protoreflect.FileDescriptor

const file_protorm_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1cprotorm/v1/annotations.proto\x12\n" +
	"protorm.v1\x1a google/protobuf/descriptor.proto\x1a\x17protorm/v1/column.proto\x1a\x1bprotorm/v1/datasource.proto\x1a\x16protorm/v1/table.proto:]\n" +
	"\n" +
	"datasource\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\v2\x1d.protorm.v1.DatasourceOptionsR\n" +
	"datasource:Q\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x18.protorm.v1.TableOptionsR\x05table:I\n" +
	"\x03col\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x16.protorm.v1.ColOptionsR\x03colBm\n" +
	"\x0ecom.protorm.v1B\x10AnnotationsProtoP\x01ZGgithub.com/the-protobuf-project/protorm/protorm/protormpbv1;protormpbv1b\x06proto3"

var file_protorm_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*DatasourceOptions)(nil),           // 3: protorm.v1.DatasourceOptions
	(*TableOptions)(nil),                // 4: protorm.v1.TableOptions
	(*ColOptions)(nil),                  // 5: protorm.v1.ColOptions
}
var file_protorm_v1_annotations_proto_depIdxs = []int32{
	0, // 0: protorm.v1.datasource:extendee -> google.protobuf.FileOptions
	1, // 1: protorm.v1.table:extendee -> google.protobuf.MessageOptions
	2, // 2: protorm.v1.col:extendee -> google.protobuf.FieldOptions
	3, // 3: protorm.v1.datasource:type_name -> protorm.v1.DatasourceOptions
	4, // 4: protorm.v1.table:type_name -> protorm.v1.TableOptions
	5, // 5: protorm.v1.col:type_name -> protorm.v1.ColOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protorm_v1_annotations_proto_init() }
func file_protorm_v1_annotations_proto_init() {
	if File_protorm_v1_annotations_proto != nil {
		return
	}
	file_protorm_v1_column_proto_init()
	file_protorm_v1_datasource_proto_init()
	file_protorm_v1_table_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protorm_v1_annotations_proto_rawDesc), len(file_protorm_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_protorm_v1_annotations_proto_goTypes,
		DependencyIndexes: file_protorm_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_protorm_v1_annotations_proto_extTypes,
	}.Build()
	File_protorm_v1_annotations_proto = out.File
	file_protorm_v1_annotations_proto_goTypes = nil
	file_protorm_v1_annotations_proto_depIdxs = nil
}
