// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protorm/v1/datasource.proto

package protormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DatasourceOptions configures database-level output for a .proto file.
// Files that share the same datasource name are merged into one database,
// so a multi-file proto package maps to a single generated schema tree.
//
// Applied via:
//
//	option (protorm.v1.datasource) = {
//	  database: "bookstore_db"
//	  schema: "bookstore"
//	  provider: "postgres"
//	  url: "postgresql://localhost:5432/bookstore_db"
//	};
type DatasourceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the explicit database identifier.
	// Defaults to the last segment of the proto package name.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// schema overrides the schema namespace for every table in this file.
	// When unset, the schema is inferred from the google.api.resource.type prefix
	// ("bookstore.v1/Book" → "bookstore_v1").
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// url is the database connection URL documented in generated config and DDL
	// headers. Prisma 7 output reads the URL from <db>.config.ts via env().
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// provider selects the database backend type system.
	// Accepted values: "postgres" (default), "mongodb".
	// Drives type mapping and the generated fragment extension
	// (<domain>.postgres.prisma vs <domain>.mongodb.prisma).
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceOptions) Reset() {
	*x = DatasourceOptions{}
	mi := &file_protorm_v1_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceOptions) ProtoMessage() {}

func (x *DatasourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protorm_v1_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceOptions.ProtoReflect.Descriptor instead.
func (*DatasourceOptions) Descriptor() ([]byte, []int) {
	return file_protorm_v1_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *DatasourceOptions) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatasourceOptions) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DatasourceOptions) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DatasourceOptions) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_protorm_v1_datasource_proto protoreflect.FileDescriptor

const file_protorm_v1_datasource_proto_rawDesc = "" +
	"\n" +
	"\x1bprotorm/v1/datasource.proto\x12\n" +
	"protorm.v1\"u\n" +
	"\x11DatasourceOptions\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bproviderBl\n" +
	"\x0ecom.protorm.v1B\x0fDatasourceProtoP\x01ZGgithub.com/the-protobuf-project/protorm/protorm/protormpbv1;protormpbv1b\x06proto3"

var (
	file_protorm_v1_datasource_proto_rawDescOnce sync.Once
	file_protorm_v1_datasource_proto_rawDescData []byte
)

func file_protorm_v1_datasource_proto_rawDescGZIP() []byte {
	file_protorm_v1_datasource_proto_rawDescOnce.Do(func() {
		file_protorm_v1_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protorm_v1_datasource_proto_rawDesc), len(file_protorm_v1_datasource_proto_rawDesc)))
	})
	return file_protorm_v1_datasource_proto_rawDescData
}

var file_protorm_v1_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protorm_v1_datasource_proto_goTypes = []any{
	(*DatasourceOptions)(nil), // 0: protorm.v1.DatasourceOptions
}
var file_protorm_v1_datasource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protorm_v1_datasource_proto_init() }
func file_protorm_v1_datasource_proto_init() {
	if File_protorm_v1_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protorm_v1_datasource_proto_rawDesc), len(file_protorm_v1_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protorm_v1_datasource_proto_goTypes,
		DependencyIndexes: file_protorm_v1_datasource_proto_depIdxs,
		MessageInfos:      file_protorm_v1_datasource_proto_msgTypes,
	}.Build()
	File_protorm_v1_datasource_proto = out.File
	file_protorm_v1_datasource_proto_goTypes = nil
	file_protorm_v1_datasource_proto_depIdxs = nil
}
