// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protorm/v1/table.proto

package protormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdStrategy selects how the primary key column is generated for a table.
// When set (not UNSPECIFIED), protorm synthesizes an `id` column as the PK and
// demotes any IDENTIFIER field to UNIQUE NOT NULL — matching the production
// pattern where AIP resource names are lookup keys, not storage keys.
type IdStrategy int32

const (
	// No synthesized key: the IDENTIFIER field stays the primary key.
	IdStrategy_ID_STRATEGY_UNSPECIFIED IdStrategy = 0
	// ULID primary key: CHAR(26), Prisma @default(ulid()), app-generated in SQL.
	IdStrategy_ID_STRATEGY_ULID IdStrategy = 1
	// UUID primary key: native UUID type, DEFAULT gen_random_uuid() in DDL,
	// Prisma @default(uuid()).
	IdStrategy_ID_STRATEGY_UUID IdStrategy = 2
)

// Enum value maps for IdStrategy.
var (
	IdStrategy_name = map[int32]string{
		0: "ID_STRATEGY_UNSPECIFIED",
		1: "ID_STRATEGY_ULID",
		2: "ID_STRATEGY_UUID",
	}
	IdStrategy_value = map[string]int32{
		"ID_STRATEGY_UNSPECIFIED": 0,
		"ID_STRATEGY_ULID":        1,
		"ID_STRATEGY_UUID":        2,
	}
)

func (x IdStrategy) Enum() *IdStrategy {
	p := new(IdStrategy)
	*p = x
	return p
}

func (x IdStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_protorm_v1_table_proto_enumTypes[0].Descriptor()
}

func (IdStrategy) Type() protoreflect.EnumType {
	return &file_protorm_v1_table_proto_enumTypes[0]
}

func (x IdStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdStrategy.Descriptor instead.
func (IdStrategy) EnumDescriptor() ([]byte, []int) {
	return file_protorm_v1_table_proto_rawDescGZIP(), []int{0}
}

// IndexDef describes one multi-column index on a table.
// Single-column indexes are expressed more concisely via ColOptions.index.
type IndexDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// columns lists field names (proto snake_case) participating in the index.
	Columns []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	// unique makes this a UNIQUE index.
	Unique bool `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
	// index is an optional explicit index name.
	// Auto-generated as idx_<table>_<cols> when empty.
	Index         string `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDef) Reset() {
	*x = IndexDef{}
	mi := &file_protorm_v1_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDef) ProtoMessage() {}

func (x *IndexDef) ProtoReflect() protoreflect.Message {
	mi := &file_protorm_v1_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDef.ProtoReflect.Descriptor instead.
func (*IndexDef) Descriptor() ([]byte, []int) {
	return file_protorm_v1_table_proto_rawDescGZIP(), []int{0}
}

func (x *IndexDef) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *IndexDef) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *IndexDef) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

// TableOptions overrides table-level generation for a message.
//
// Applied via:
//
//	option (protorm.v1.table) = {
//	  table: "shelves"
//	  id: ID_STRATEGY_ULID
//	  timestamps: true
//	};
type TableOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is an explicit table name.
	// Defaults to snake_case plural of the google.api.resource.type suffix.
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// skip excludes this message from all output — no table is generated.
	Skip bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// indexes declares additional multi-column indexes beyond those inferred
	// from AIP annotations (e.g. composite unique constraints).
	Indexes []*IndexDef `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty"`
	// id synthesizes a generated primary key column (ULID or UUID) and demotes
	// the IDENTIFIER field to a UNIQUE constraint.
	Id IdStrategy `protobuf:"varint,4,opt,name=id,proto3,enum=protorm.v1.IdStrategy" json:"id,omitempty"`
	// timestamps appends created_at / updated_at TIMESTAMPTZ columns:
	// created_at DEFAULT now(); updated_at maintained on write
	// (Prisma @updatedAt, GORM autoUpdateTime).
	Timestamps    bool `protobuf:"varint,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableOptions) Reset() {
	*x = TableOptions{}
	mi := &file_protorm_v1_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableOptions) ProtoMessage() {}

func (x *TableOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protorm_v1_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableOptions.ProtoReflect.Descriptor instead.
func (*TableOptions) Descriptor() ([]byte, []int) {
	return file_protorm_v1_table_proto_rawDescGZIP(), []int{1}
}

func (x *TableOptions) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *TableOptions) GetIndexes() []*IndexDef {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *TableOptions) GetId() IdStrategy {
	if x != nil {
		return x.Id
	}
	return IdStrategy_ID_STRATEGY_UNSPECIFIED
}

func (x *TableOptions) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

var File_protorm_v1_table_proto protoreflect.FileDescriptor

const file_protorm_v1_table_proto_rawDesc = "" +
	"\n" +
	"\x16protorm/v1/table.proto\x12\n" +
	"protorm.v1\"R\n" +
	"\bIndexDef\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x02 \x01(\bR\x06unique\x12\x14\n" +
	"\x05index\x18\x03 \x01(\tR\x05index\"\xb0\x01\n" +
	"\fTableOptions\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12.\n" +
	"\aindexes\x18\x03 \x03(\v2\x14.protorm.v1.IndexDefR\aindexes\x12&\n" +
	"\x02id\x18\x04 \x01(\x0e2\x16.protorm.v1.IdStrategyR\x02id\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\bR\n" +
	"timestamps*U\n" +
	"\n" +
	"IdStrategy\x12\x1b\n" +
	"\x17ID_STRATEGY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ID_STRATEGY_ULID\x10\x01\x12\x14\n" +
	"\x10ID_STRATEGY_UUID\x10\x02Bg\n" +
	"\x0ecom.protorm.v1B\n" +
	"TableProtoP\x01ZGgithub.com/the-protobuf-project/protorm/protorm/protormpbv1;protormpbv1b\x06proto3"

var (
	file_protorm_v1_table_proto_rawDescOnce sync.Once
	file_protorm_v1_table_proto_rawDescData []byte
)

func file_protorm_v1_table_proto_rawDescGZIP() []byte {
	file_protorm_v1_table_proto_rawDescOnce.Do(func() {
		file_protorm_v1_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protorm_v1_table_proto_rawDesc), len(file_protorm_v1_table_proto_rawDesc)))
	})
	return file_protorm_v1_table_proto_rawDescData
}

var file_protorm_v1_table_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protorm_v1_table_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protorm_v1_table_proto_goTypes = []any{
	(IdStrategy)(0),      // 0: protorm.v1.IdStrategy
	(*IndexDef)(nil),     // 1: protorm.v1.IndexDef
	(*TableOptions)(nil), // 2: protorm.v1.TableOptions
}
var file_protorm_v1_table_proto_depIdxs = []int32{
	1, // 0: protorm.v1.TableOptions.indexes:type_name -> protorm.v1.IndexDef
	0, // 1: protorm.v1.TableOptions.id:type_name -> protorm.v1.IdStrategy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protorm_v1_table_proto_init() }
func file_protorm_v1_table_proto_init() {
	if File_protorm_v1_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protorm_v1_table_proto_rawDesc), len(file_protorm_v1_table_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protorm_v1_table_proto_goTypes,
		DependencyIndexes: file_protorm_v1_table_proto_depIdxs,
		EnumInfos:         file_protorm_v1_table_proto_enumTypes,
		MessageInfos:      file_protorm_v1_table_proto_msgTypes,
	}.Build()
	File_protorm_v1_table_proto = out.File
	file_protorm_v1_table_proto_goTypes = nil
	file_protorm_v1_table_proto_depIdxs = nil
}
