-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: aip.proto
--
-- database: v1
-- schema:   aip_v1
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "aip_v1";

-- Document exercises the AIP-148/164 system fields: create_time/update_time become auto-managed audit timestamps, delete_time a nullable indexed soft-delete marker, and uid a UNIQUE server-assigned id — all with no protorm annotation.
CREATE TABLE "aip_v1"."documents" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- uid is the server-assigned unique id (AIP-148).
    "uid"  VARCHAR(255)  UNIQUE,
    -- title is an ordinary required field.
    "title"  VARCHAR(255)  NOT NULL,
    -- create_time is set by the server on creation (AIP-148).
    "create_time"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- update_time is maintained by the server on every write (AIP-148).
    "update_time"  TIMESTAMPTZ  NOT NULL,
    -- delete_time marks a soft-deleted row when set (AIP-164).
    "delete_time"  TIMESTAMPTZ
);
CREATE INDEX "idx_documents_delete_time" ON "aip_v1"."documents" ("delete_time");
