-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: bookstore.proto
--
-- database: bookstore_db
-- schema:   bookstore_v1
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "bookstore_v1";

-- Genre classifies a book's literary category.
CREATE TYPE "bookstore_v1"."genre" AS ENUM ('FICTION', 'NON_FICTION', 'SCI_FI', 'FANTASY');

-- Author is a top-level resource. Inferred table: bookstore_v1.authors. id: ID_STRATEGY_ULID synthesizes a generated `id` PK and demotes the AIP resource name to a UNIQUE lookup column; timestamps adds created_at/updated_at.
CREATE TABLE "bookstore_v1"."authors" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name is the AIP resource name; UNIQUE NOT NULL lookup key (id is the PK).
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- display_name is REQUIRED → NOT NULL; string → VARCHAR(255) default.
    "display_name"  VARCHAR(255)  NOT NULL,
    -- bio is free-form; override the VARCHAR(255) default to unbounded TEXT, nullable.
    "bio"  TEXT,
    -- Timestamp when the record was created.
    "created_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- Timestamp when the record was last updated.
    "updated_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now()
);

-- Book is a resource nested under Author. Inferred table: bookstore_v1.books.
CREATE TABLE "bookstore_v1"."books" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- title: REQUIRED NOT NULL; max_length caps the VARCHAR provider-neutrally.
    "title"  VARCHAR(500)  NOT NULL,
    -- author_id references Author; protorm infers the FOREIGN KEY, aligns the column type with the referenced PK (CHAR(26) ULID), and applies CASCADE.
    "author_id"  CHAR(26)  NOT NULL,
    -- isbn must be globally unique; custom fixed-width type.
    "isbn"  VARCHAR(13)  UNIQUE,
    -- published_year is a plain integer column; nullable.
    "published_year"  INTEGER,
    -- genre demonstrates proto enum → database enum generation.
    "genre"  "bookstore_v1"."genre"  NOT NULL  DEFAULT 'FICTION',
    -- create_time is set by the database on insert.
    "create_time"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    CONSTRAINT "fk_books_author_id" FOREIGN KEY ("author_id") REFERENCES "bookstore_v1"."authors"("id") ON DELETE CASCADE
);
CREATE INDEX "idx_books_author_year" ON "bookstore_v1"."books" ("author_id", "published_year");
CREATE INDEX "idx_books_author_id" ON "bookstore_v1"."books" ("author_id");
