-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: fleet.proto
--
-- database: fleet
-- schema:   fleet_tracking_device
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "fleet_tracking_device";

-- Tracker is a fleet device resource. The layout config routes it to the "fleet" database, schema "fleet_tracking_device".
CREATE TABLE "fleet_tracking_device"."trackers" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- serial is the device's hardware serial number.
    "serial"  VARCHAR(255)  NOT NULL
);
