// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
// source: uniqueindex.proto
//
// database: promo_db
// schema:   promo
//
// protorm — https://github.com/the-protobuf-project/protorm

package promo

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// PromoCodeStore provides typed CRUD access to PromoCode records.
// PromoCode is a redeemable promotion. The human-facing `code` is unique via a single-column unique index, so protorm emits GetByCode alongside GetByID and the GetByName finder for the AIP resource name.
type PromoCodeStore struct{ DB *gorm.DB }

// Compile-time proof that PromoCodeStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[PromoCode] = (*PromoCodeStore)(nil)

// NewPromoCodeStore returns a PromoCodeStore backed by db.
func NewPromoCodeStore(db *gorm.DB) *PromoCodeStore { return &PromoCodeStore{DB: db} }

// Create inserts m.
func (s *PromoCodeStore) Create(ctx context.Context, m *PromoCode) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the PromoCode records matching opts.
func (s *PromoCodeStore) List(ctx context.Context, opts gormx.ListOptions) ([]PromoCode, error) {
	var out []PromoCode
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of PromoCode records matching opts.Where
// (pagination and ordering are ignored).
func (s *PromoCodeStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&PromoCode{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *PromoCodeStore) Update(ctx context.Context, m *PromoCode) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the PromoCode with the given primary key.
func (s *PromoCodeStore) GetByID(ctx context.Context, id string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the PromoCode with the given primary key.
func (s *PromoCodeStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&PromoCode{}, "id = ?", id).Error
}

// GetByName fetches the PromoCode with the given name (a unique column).
func (s *PromoCodeStore) GetByName(ctx context.Context, v string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// GetByCode fetches the PromoCode with the given code (a unique column).
func (s *PromoCodeStore) GetByCode(ctx context.Context, v string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "code = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
