-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: billing.proto
--
-- database: billing_db
-- schema:   acme_billing
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "acme_billing";

-- Invoice lands in schema "acme_billing", not "acme_billing_v1": the protorm.yaml strip_version option flattens the trailing API version out of the resource-type-derived schema name.
CREATE TABLE "acme_billing"."invoices" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Amount due, in minor units.
    "amount"  VARCHAR(255)  NOT NULL
);
