// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
//
// database: freebusy_db
// schemas:  promocode, billing, common
//
// Migration aggregator: every model in one factory Registry.
//
// protorm — https://github.com/the-protobuf-project/protorm

// Package freebusydb wires every model generated for the freebusy_db database
// into one factory Registry, so an application can migrate the whole database in
// a single call. Default is preloaded with every generated model; Register adds
// your own.
package freebusydb

import (
	billing "example.com/test/gen/freebusy_db/billing"
	common "example.com/test/gen/freebusy_db/common"
	promocode "example.com/test/gen/freebusy_db/promocode"

	"gorm.io/gorm"
	"gorm.io/plugin/opentelemetry/tracing"
)

// Migrator is the subset of *gorm.DB the Migrate call needs; *gorm.DB satisfies
// it. EnsureSchemas and Instrument take a concrete *gorm.DB, since creating
// schemas and installing plugins need the full driver.
type Migrator interface {
	AutoMigrate(models ...any) error
}

// schemas lists every Postgres schema the registered models live in, so
// EnsureSchemas can create them before AutoMigrate builds schema-qualified tables.
var schemas = []string{
	"promocode",
	"billing",
	"common",
}

// Registry collects GORM models so they migrate together.
type Registry struct {
	models []any
}

// New returns an empty Registry.
func New() *Registry { return &Registry{} }

// Register appends models to the registry and returns it for chaining.
func (r *Registry) Register(models ...any) *Registry {
	r.models = append(r.models, models...)
	return r
}

// Models returns every registered model, in registration order.
func (r *Registry) Models() []any { return r.models }

// Migrate runs AutoMigrate for every registered model.
func (r *Registry) Migrate(db Migrator) error {
	return db.AutoMigrate(r.models...)
}

// EnsureSchemas creates every Postgres schema the registered models live in, if
// it does not already exist. AutoMigrate does not create schemas, so call this
// before Migrate when models map to schema-qualified tables:
//
//	if err := freebusydb.Default.EnsureSchemas(db); err != nil {
//		log.Fatal(err)
//	}
//	if err := freebusydb.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
func (*Registry) EnsureSchemas(db *gorm.DB) error {
	for _, name := range schemas {
		if err := db.Exec(`CREATE SCHEMA IF NOT EXISTS "` + name + `"`).Error; err != nil {
			return err
		}
	}
	return nil
}

// Default holds every model generated for the freebusy_db database. Attach it
// in your application's startup:
//
//	if err := freebusydb.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
//
// Register your own models alongside the generated ones:
//
//	freebusydb.Default.Register(&MyModel{})
var Default = New().Register(
	&promocode.PromoCode{},
	&promocode.Redemption{},
	&billing.Invoice{},
	&common.Money{},
)

// Instrument installs the OpenTelemetry GORM plugin on db, so every query the
// application runs emits an OpenTelemetry span (and metric). Call it once at
// startup, after opening the connection and before serving traffic:
//
//	if err := freebusydb.Default.Instrument(db); err != nil {
//		log.Fatal(err)
//	}
//
// Pass extra tracing.Option values to customize at the call site, e.g.
// tracing.WithAttributes(...) or tracing.WithoutQueryVariables().
func (*Registry) Instrument(db *gorm.DB, opts ...tracing.Option) error {
	defaults := []tracing.Option{}
	return db.Use(tracing.NewPlugin(append(defaults, opts...)...))
}
