-- Code generated by protoc-gen-protorm. DO NOT EDIT.
--
-- Database: wkt_db
-- Schema:   kitchen

CREATE SCHEMA IF NOT EXISTS kitchen;

-- Sink is one table holding every interesting type mapping.
CREATE TABLE kitchen.sinks (
    -- name: IDENTIFIER → PRIMARY KEY.
    name  VARCHAR(255)  NOT NULL  PRIMARY KEY,
    -- bool → BOOLEAN.
    flag  BOOLEAN,
    -- int32 → INTEGER.
    count32  INTEGER,
    -- int64 → BIGINT.
    count64  BIGINT,
    -- float → REAL.
    ratio  REAL,
    -- double → DOUBLE PRECISION.
    precise  DOUBLE PRECISION,
    -- bytes → BYTEA.
    blob  BYTEA,
    -- Timestamp → TIMESTAMPTZ.
    event_time  TIMESTAMPTZ,
    -- Duration → INTERVAL.
    window  INTERVAL,
    -- FieldMask → TEXT.
    mask  TEXT,
    -- Int64 wrapper → BIGINT.
    maybe_count  BIGINT,
    -- String wrapper → VARCHAR(255).
    maybe_label  VARCHAR(255),
    -- repeated string → VARCHAR(255)[].
    tags  VARCHAR(255)[],
    -- repeated int32 → INTEGER[].
    scores  INTEGER[],
    -- map → JSONB.
    attributes  JSONB
);
