// Package header renders the banner comment placed at the top of every
// generated file. The layout follows protoc-gen-go's convention — a versions
// block and a source line — with protorm's database/schema metadata and a
// project link appended.
package header

import "strings"

// project credits the generator and its authors.
const project = "protorm — https://github.com/the-protobuf-project/protorm"

// Info is the metadata rendered into one file's banner. Source and Notes may be
// empty; the umbrella datasource file, for instance, aggregates schemas and has
// no single source proto.
type Info struct {
	PluginVersion string   // protoc-gen-protorm version (build ldflags)
	ProtocVersion string   // protoc compiler version (CodeGeneratorRequest)
	Source        string   // originating .proto path(s); omitted when empty
	Database      string   // datasource database name
	SchemaLabel   string   // "schema" or "schemas"; defaults to "schema"
	Schema        string   // schema name, or schemas list for the umbrella file
	Notes         []string // extra context lines, shown before the project line
}

// Render returns the banner with every line prefixed by prefix ("//" for Go,
// Prisma, and TypeScript; "--" for SQL). Blank separators are emitted as the
// bare prefix with no trailing space, matching the protoc-gen-go convention.
func Render(prefix string, in Info) string {
	lines := []string{
		"Code generated by protoc-gen-protorm. DO NOT EDIT.",
		"versions:",
		"\tprotoc-gen-protorm " + orUnknown(in.PluginVersion),
		"\tprotoc             " + orUnknown(in.ProtocVersion),
	}
	if in.Source != "" {
		lines = append(lines, "source: "+in.Source)
	}

	label := in.SchemaLabel
	if label == "" {
		label = "schema"
	}
	lines = append(lines, "", pad("database")+in.Database, pad(label)+in.Schema)

	if len(in.Notes) > 0 {
		lines = append(lines, "")
		lines = append(lines, in.Notes...)
	}
	lines = append(lines, "", project)

	var b strings.Builder
	for i, ln := range lines {
		if i > 0 {
			b.WriteByte('\n')
		}
		if ln == "" {
			b.WriteString(prefix)
		} else {
			b.WriteString(prefix + " " + ln)
		}
	}
	return b.String()
}

// pad right-pads a metadata label so its values align in a column:
// "database: ", "schema:   ", "schemas:  ".
func pad(label string) string {
	const width = 10 // len("database: ")
	s := label + ":"
	if n := width - len(s); n > 0 {
		s += strings.Repeat(" ", n)
	}
	return s
}

// orUnknown substitutes the protoc-gen-go sentinel for a missing version.
func orUnknown(v string) string {
	if v == "" {
		return "(unknown)"
	}
	return v
}
