package header

import "testing"

func TestRender(t *testing.T) {
	got := Render("//", Info{
		PluginVersion: "v0.1.0",
		ProtocVersion: "v5.29.0",
		Source:        "bookstore/v1/bookstore.proto",
		Database:      "bookstore_db",
		Schema:        "bookstore_v1",
	})
	want := "// Code generated by protoc-gen-protorm. DO NOT EDIT.\n" +
		"// versions:\n" +
		"// \tprotoc-gen-protorm v0.1.0\n" +
		"// \tprotoc             v5.29.0\n" +
		"// source: bookstore/v1/bookstore.proto\n" +
		"//\n" +
		"// database: bookstore_db\n" +
		"// schema:   bookstore_v1\n" +
		"//\n" +
		"// protorm — https://github.com/the-protobuf-project/protorm"
	if got != want {
		t.Errorf("Render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderSQLPrefixUnknownVersionsAndNotes(t *testing.T) {
	// "--" prefix, missing versions render as "(unknown)", no source line, the
	// "schemas" label aligns its value, and Notes appear before the project line.
	got := Render("--", Info{
		Database:    "bookstore_db",
		SchemaLabel: "schemas",
		Schema:      "bookstore_v1, inventory",
		Notes:       []string{"a note."},
	})
	want := "-- Code generated by protoc-gen-protorm. DO NOT EDIT.\n" +
		"-- versions:\n" +
		"-- \tprotoc-gen-protorm (unknown)\n" +
		"-- \tprotoc             (unknown)\n" +
		"--\n" +
		"-- database: bookstore_db\n" +
		"-- schemas:  bookstore_v1, inventory\n" +
		"--\n" +
		"-- a note.\n" +
		"--\n" +
		"-- protorm — https://github.com/the-protobuf-project/protorm"
	if got != want {
		t.Errorf("Render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}
