<!-- Code generated by protoc-gen-protorm. DO NOT EDIT. -->

# {{.Database}} — Prisma schema

Generated from Protobuf by [protoc-gen-protorm](https://github.com/the-protobuf-project/protorm).
The source of truth is the `.proto` files — regenerate rather than editing these.

## Layout

```
{{.Database}}/
├── {{.Database}}.config.ts   Prisma 7 config (datasource URL via env)
├── schema.prisma             datasource + generator blocks
├── <schema>/<domain>.{{.ProviderExt}}.prisma   models & enums, one file per source proto
├── package.json
├── tsconfig.json
└── .env.example
```

## Setup

```bash
npm install
cp .env.example .env        # then edit {{.EnvVar}}
npm run prisma:generate     # generate the typed client
npm run prisma:migrate      # create & apply a dev migration
```

All scripts target `{{.Database}}.config.ts` via `--config`.
