// =============================================================================
// Code generated by protoc-gen-protorm. DO NOT EDIT.
//
// Database : {{.Database}}
// Schemas  : {{.SchemaCSV}}
//
// Connection URLs live in {{.Database}}.config.ts (Prisma 7 convention) —
// schema files no longer carry a url property.
//
// Generator : protoc-gen-protorm (https://github.com/oh-tarnished/protorm)
// Authors   : oh-tarnished/protorm contributors
// =============================================================================

datasource {{.Datasource}} {
  provider = "{{.Provider}}"
{{- if .MultiSchema}}
  schemas  = [{{.SchemaList}}]
{{- end}}
}

generator client {
  provider = "prisma-client"
  output   = "./generated/client"
}
