// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
//
// database: v1
// schemas:  aip_v1
//
// Migration aggregator: every model in one factory Registry.
//
// protorm — https://github.com/the-protobuf-project/protorm

// Package v1 wires every model generated for the v1 database
// into one factory Registry, so an application can migrate the whole database in
// a single call. Default is preloaded with every generated model; Register adds
// your own.
package v1

import (
	aipv1 "example.com/test/gen/v1/aipv1"

	"gorm.io/gorm"
	"gorm.io/plugin/opentelemetry/tracing"
)

// Migrator is the subset of *gorm.DB the registry needs. *gorm.DB already
// satisfies it, so this package depends on no external module.
type Migrator interface {
	AutoMigrate(models ...any) error
}

// Registry collects GORM models so they migrate together.
type Registry struct {
	models []any
}

// New returns an empty Registry.
func New() *Registry { return &Registry{} }

// Register appends models to the registry and returns it for chaining.
func (r *Registry) Register(models ...any) *Registry {
	r.models = append(r.models, models...)
	return r
}

// Models returns every registered model, in registration order.
func (r *Registry) Models() []any { return r.models }

// Migrate runs AutoMigrate for every registered model.
func (r *Registry) Migrate(db Migrator) error {
	return db.AutoMigrate(r.models...)
}

// Default holds every model generated for the v1 database. Attach it
// in your application's startup:
//
//	if err := v1.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
//
// Register your own models alongside the generated ones:
//
//	v1.Default.Register(&MyModel{})
var Default = New().Register(
	&aipv1.Document{},
)

// Instrument installs the OpenTelemetry GORM plugin on db, so every query the
// application runs emits an OpenTelemetry span (and metric). Call it once at
// startup, after opening the connection and before serving traffic:
//
//	if err := v1.Default.Instrument(db); err != nil {
//		log.Fatal(err)
//	}
//
// Pass extra tracing.Option values to customize at the call site, e.g.
// tracing.WithAttributes(...) or tracing.WithoutQueryVariables().
func (*Registry) Instrument(db *gorm.DB, opts ...tracing.Option) error {
	defaults := []tracing.Option{}
	return db.Use(tracing.NewPlugin(append(defaults, opts...)...))
}
