// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
//
// database: users
// schemas:  calendar_app
//
// Migration aggregator: every model in one factory Registry.
//
// protorm — https://github.com/the-protobuf-project/protorm

// Package users wires every model generated for the users database
// into one factory Registry, so an application can migrate the whole database in
// a single call. Default is preloaded with every generated model; Register adds
// your own.
package users

import (
	calendarapp "example.com/test/gen/users/calendarapp"
)

// Migrator is the subset of *gorm.DB the registry needs. *gorm.DB already
// satisfies it, so this package depends on no external module.
type Migrator interface {
	AutoMigrate(models ...any) error
}

// Registry collects GORM models so they migrate together.
type Registry struct {
	models []any
}

// New returns an empty Registry.
func New() *Registry { return &Registry{} }

// Register appends models to the registry and returns it for chaining.
func (r *Registry) Register(models ...any) *Registry {
	r.models = append(r.models, models...)
	return r
}

// Models returns every registered model, in registration order.
func (r *Registry) Models() []any { return r.models }

// Migrate runs AutoMigrate for every registered model.
func (r *Registry) Migrate(db Migrator) error {
	return db.AutoMigrate(r.models...)
}

// Default holds every model generated for the users database. Attach it
// in your application's startup:
//
//	if err := users.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
//
// Register your own models alongside the generated ones:
//
//	users.Default.Register(&MyModel{})
var Default = New().Register(
	&calendarapp.Event{},
)
