-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: store.proto
--
-- database: users
-- schema:   calendar_app
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "calendar_app";

-- Event is a calendar app resource. The layout config routes it to the "users" database, schema "calendar_app".
CREATE TABLE "calendar_app"."events" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- title is the event's display title.
    "title"  VARCHAR(255)  NOT NULL
);
