-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
--
-- database: users
-- schemas:  calendar_app
--
-- Single-file migration: every schema, applied in one transaction.
--
-- protorm — https://github.com/the-protobuf-project/protorm

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "calendar_app";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Event is a calendar app resource. The layout config routes it to the "users" database, schema "calendar_app".
CREATE TABLE "calendar_app"."events" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- title is the event's display title.
    "title"  VARCHAR(255)  NOT NULL
);

-- Documentation
COMMENT ON TABLE "calendar_app"."events" IS 'Event is a calendar app resource. The layout config routes it to the "users" database, schema "calendar_app".';
COMMENT ON COLUMN "calendar_app"."events"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "calendar_app"."events"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "calendar_app"."events"."title" IS 'title is the event''s display title.';

COMMIT;
