// Code generated by protoc-gen-protorm. DO NOT EDIT.
//
// Database: bookstore_db
// Schema:   bookstore_v1

package bookstorev1

import (
	"time"
)

// Genre classifies a book's literary category.
type Genre string

// Genre values as stored in the database.
const (
	GenreUnspecified Genre = "unspecified"
	GenreFiction     Genre = "fiction"
	GenreNonFiction  Genre = "non_fiction"
	GenreSciFi       Genre = "sci_fi"
	GenreFantasy     Genre = "fantasy"
)

// Author is a top-level resource. Inferred table: bookstore_v1.authors. id: ID_STRATEGY_ULID synthesizes a generated `id` PK and demotes the AIP resource name to a UNIQUE lookup column; timestamps adds created_at/updated_at.
type Author struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// name is the AIP resource name; UNIQUE NOT NULL lookup key (id is the PK).
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// display_name is REQUIRED → NOT NULL; string → VARCHAR(255) default.
	DisplayName string `gorm:"column:display_name;not null" json:"display_name" validate:"required"`
	// bio is free-form; override the VARCHAR(255) default to unbounded TEXT, nullable.
	Bio *string `gorm:"column:bio" json:"bio,omitempty"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	// Timestamp when the record was last updated.
	UpdatedAt time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`
	// Back-relation: Book records that reference this via author_id.
	Books []Book `gorm:"foreignKey:AuthorID" json:"books,omitempty"`
}

func (*Author) TableName() string { return "bookstore_v1.authors" }

// Book is a resource nested under Author. Inferred table: bookstore_v1.books.
type Book struct {
	// name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).
	Name string `gorm:"column:name;primaryKey;not null" json:"name"`
	// title: REQUIRED NOT NULL; max_length caps the VARCHAR provider-neutrally.
	Title string `gorm:"column:title;not null" json:"title" validate:"required"`
	// author_id references Author; protorm infers the FOREIGN KEY, aligns the column type with the referenced PK (CHAR(26) ULID), and applies CASCADE.
	AuthorID string  `gorm:"column:author_id;not null" json:"author_id" validate:"required"`
	Author   *Author `gorm:"foreignKey:AuthorID;constraint:OnDelete:CASCADE" json:"author,omitempty"`
	// isbn must be globally unique; custom fixed-width type.
	ISBN *string `gorm:"column:isbn;uniqueIndex" json:"isbn,omitempty"`
	// published_year is a plain integer column; nullable.
	PublishedYear *int32 `gorm:"column:published_year" json:"published_year,omitempty"`
	// genre demonstrates proto enum → database enum generation.
	Genre Genre `gorm:"column:genre;not null" json:"genre" validate:"required"`
	// create_time is set by the database on insert.
	CreateTime *time.Time `gorm:"column:create_time;default:now()" json:"create_time,omitempty"`
}

func (*Book) TableName() string { return "bookstore_v1.books" }
