// Code generated by protoc-gen-protorm. DO NOT EDIT.
//
// Database: bookstore_db
// Schema:   inventory

package inventory

import (
	"time"
)

// Shelf groups books physically. The resource's `plural` fixes the irregular plural ("shelfs" → "shelves") — no table name override needed.
type Shelf struct {
	// name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).
	Name string `gorm:"column:name;primaryKey;not null" json:"name"`
	// theme: REQUIRED → NOT NULL VARCHAR(255).
	Theme string `gorm:"column:theme;not null" json:"theme" validate:"required"`
	// capacity is the number of books the shelf holds; nullable INTEGER.
	Capacity *int32 `gorm:"column:capacity" json:"capacity,omitempty"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	// Timestamp when the record was last updated.
	UpdatedAt time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`
}

func (*Shelf) TableName() string { return "inventory.shelves" }
