-- Code generated by protoc-gen-protorm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-protorm (unknown)
-- 	protoc             (unknown)
-- source: oneof.proto
--
-- database: v1
-- schema:   oneof_v1
--
-- protorm — https://github.com/the-protobuf-project/protorm

CREATE SCHEMA IF NOT EXISTS "oneof_v1";

-- Discriminator for the input oneof of Audio.
CREATE TYPE "oneof_v1"."audio_input_case" AS ENUM ('AUDIO_DATA', 'UPLOAD_PATH', 'LIVE_PIPELINE_FILE_PATH');

-- Audio exercises oneof integrity: the `input` oneof flattens to independent nullable columns, and protorm adds a generated input_case discriminator enum recording which member is set so the lost exclusivity invariant is observable.
CREATE TABLE "oneof_v1"."audios" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Inline audio bytes.
    "audio_data"  BYTEA,
    -- Path to a previously uploaded file.
    "upload_path"  VARCHAR(255),
    -- Path to a file produced by a live pipeline.
    "live_pipeline_file_path"  VARCHAR(255),
    -- sample_rate is a plain scalar outside the oneof.
    "sample_rate"  INTEGER,
    -- Discriminator: which input oneof member is set (null = none).
    "input_case"  "oneof_v1"."audio_input_case"
);
