package prisma

// readme.go documents the generated Prisma tree. It writes a README.md into
// every folder of the mirrored layout — leaf fragment folders and the
// intermediate/root folders above them — each carrying a Mermaid ER diagram of
// the models in (or under) that folder, plus model/enum detail for leaves.
//
// Unlike the standalone schema_readme generator this replaces, the diagram is
// built directly from the protorm IR (tables, foreign keys, resolved PK
// columns) rather than by re-parsing .prisma text.

import (
	"fmt"
	"log"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/oh-tarnished/protorm/plugin/generator/schema"
	"github.com/oh-tarnished/protorm/plugin/generator/types"
)

const readmeMarker = "<!-- Code generated by protoc-gen-protorm. DO NOT EDIT. -->\n\n"

// writeReadmes emits a README.md for every directory in the database's output
// tree: leaf folders get full model/enum detail, ancestors get a subtree index.
// Both carry a Mermaid ER diagram of the models in their subtree.
func writeReadmes(p *protogen.Plugin, db *schema.Database, groups []fragmentGroup, provider types.Provider) error {
	dirs := map[string]*node{}
	get := func(dir string) *node {
		n := dirs[dir]
		if n == nil {
			n = &node{}
			dirs[dir] = n
		}
		return n
	}

	for _, g := range groups {
		leaf := fragmentDir(db.Name, g.sourceDir, g.fileBase)
		get(leaf).fragments = append(get(leaf).fragments, g)
		// Attribute the group's tables/enums to this dir and every ancestor so a
		// parent README aggregates its whole subtree.
		for _, dir := range ancestors(db.Name, leaf) {
			n := get(dir)
			n.tables = append(n.tables, g.tables...)
			n.enums = append(n.enums, g.enums...)
		}
	}

	for dir, n := range dirs {
		md := readmeMarker + renderReadme(db, dir, n.tables, n.enums, n.fragments, childDirs(dir, dirs), provider)
		f := p.NewGeneratedFile(dir+"/README.md", "")
		if _, err := f.Write([]byte(md)); err != nil {
			return fmt.Errorf("prisma: %s/README.md: %w", dir, err)
		}
	}
	return nil
}

// ancestors lists dir and every parent directory down to (and including) the
// database root. "users/apps/calendar" under root "users" →
// ["users", "users/apps", "users/apps/calendar"].
func ancestors(root, dir string) []string {
	if dir == root || !strings.HasPrefix(dir, root+"/") {
		return []string{dir}
	}
	rest := strings.Split(strings.TrimPrefix(dir, root+"/"), "/")
	out := []string{root}
	cur := root
	for _, seg := range rest {
		cur += "/" + seg
		out = append(out, cur)
	}
	return out
}

// childDirs returns the immediate subdirectories of dir present in the tree.
func childDirs(dir string, dirs map[string]*node) []string {
	seen := map[string]bool{}
	var out []string
	for d := range dirs {
		if !strings.HasPrefix(d, dir+"/") {
			continue
		}
		child := dir + "/" + strings.SplitN(strings.TrimPrefix(d, dir+"/"), "/", 2)[0]
		if !seen[child] {
			seen[child] = true
			out = append(out, child)
		}
	}
	sort.Strings(out)
	return out
}

// node accumulates the tables, enums, and direct fragments of one output
// directory's subtree while READMEs are assembled.
type node struct {
	tables    []*schema.Table
	enums     []*schema.Enum
	fragments []fragmentGroup
}

// renderReadme builds the markdown body for one folder.
func renderReadme(db *schema.Database, dir string, tables []*schema.Table, enums []*schema.Enum, fragments []fragmentGroup, children []string, provider types.Provider) string {
	var b strings.Builder
	rel := strings.TrimPrefix(dir, db.Name)
	rel = strings.TrimPrefix(rel, "/")
	if rel == "" {
		rel = "(root)"
	}
	log.Printf("rel: %s", rel)
	fmt.Fprintf(&b, "# `%s/` — Prisma schema\n\n", dir)
	fmt.Fprintf(&b, "Generated from Protobuf by protoc-gen-protorm. Source of truth is the `.proto` files — regenerate rather than editing.\n\n")
	fmt.Fprintf(&b, "| Models | Enums |\n| ---: | ---: |\n| %d | %d |\n\n", len(uniqueTables(tables)), len(uniqueEnums(enums)))

	b.WriteString(mermaidER(uniqueTables(tables)))

	if len(children) > 0 {
		b.WriteString("## Subfolders\n\n")
		for _, c := range children {
			name := c[strings.LastIndexByte(c, '/')+1:]
			fmt.Fprintf(&b, "- [`%s/`](./%s/README.md)\n", name, name)
		}
		b.WriteString("\n")
	}
	for _, g := range fragments {
		file := g.fileBase + "." + provider.FragmentExt() + ".prisma"
		fmt.Fprintf(&b, "Schema file: [`%s`](./%s)\n\n", file, file)
		writeModelDetail(&b, g.tables, g.enums)
	}
	return b.String()
}

// mermaidER renders an erDiagram with PK/FK columns and crow's-foot edges.
// Models referenced but not in this set become external stub entities.
func mermaidER(tables []*schema.Table) string {
	if len(tables) == 0 {
		return ""
	}
	defined := map[string]bool{}
	for _, t := range tables {
		defined[t.ModelName] = true
	}

	var b strings.Builder
	b.WriteString("## Entity relationships\n\n```mermaid\nerDiagram\n    direction LR\n")

	stubs := map[string]bool{}
	sorted := append([]*schema.Table(nil), tables...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ModelName < sorted[j].ModelName })

	for _, t := range sorted {
		pk := map[string]bool{}
		if t.PKColumn != "" {
			pk[t.PKColumn] = true
		}
		fk := map[string]bool{}
		for _, f := range t.ForeignKeys {
			fk[f.Column] = true
			if !defined[f.ReferencedModel] {
				stubs[f.ReferencedModel] = true
			}
		}
		fmt.Fprintf(&b, "    %s {\n", mermaidID(t.ModelName))
		any := false
		for _, c := range t.Columns {
			if !pk[c.Name] && !fk[c.Name] {
				continue
			}
			tag := ""
			switch {
			case pk[c.Name] && fk[c.Name]:
				tag = "PK, FK"
			case pk[c.Name]:
				tag = "PK"
			default:
				tag = "FK"
			}
			fmt.Fprintf(&b, "        %s %s %s\n", erType(c), safeIdent(c.Name), tag)
			any = true
		}
		if !any {
			b.WriteString("        string id PK\n")
		}
		b.WriteString("    }\n")
	}
	for _, name := range sortedKeys(stubs) {
		fmt.Fprintf(&b, "    %s {\n        string externalStub PK\n    }\n", mermaidID(name))
	}
	for _, t := range sorted {
		for _, f := range t.ForeignKeys {
			fmt.Fprintf(&b, "    %s }o--|| %s : \"%s\"\n",
				mermaidID(t.ModelName), mermaidID(f.ReferencedModel), f.Column)
		}
	}
	b.WriteString("```\n\n")
	return b.String()
}

// writeModelDetail emits per-model field tables and the enum list for a leaf.
func writeModelDetail(b *strings.Builder, tables []*schema.Table, enums []*schema.Enum) {
	for _, t := range tables {
		fmt.Fprintf(b, "### `%s`", t.ModelName)
		if t.Name != "" {
			fmt.Fprintf(b, " → `%s`", t.Name)
		}
		b.WriteString("\n\n")
		if t.Comment != "" {
			fmt.Fprintf(b, "%s\n\n", escapeCell(t.Comment))
		}
		b.WriteString("| Column | Type | Null |\n| --- | --- | --- |\n")
		for _, c := range t.Columns {
			null := "not null"
			if c.Optional {
				null = "nullable"
			}
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", c.Name, columnType(c), null)
		}
		b.WriteString("\n")
	}
	if len(enums) > 0 {
		b.WriteString("### Enums\n\n")
		for _, e := range enums {
			vals := make([]string, len(e.Values))
			for i, v := range e.Values {
				vals[i] = v.Name
			}
			fmt.Fprintf(b, "- `%s`: %s\n", e.Name, strings.Join(vals, ", "))
		}
		b.WriteString("\n")
	}
}

func columnType(c *schema.Column) string {
	if c.Enum != nil {
		return c.Enum.Name
	}
	return c.SQLType
}

// erType maps a column to a Mermaid-safe attribute type keyword.
func erType(c *schema.Column) string {
	if c.Enum != nil {
		return "string"
	}
	base, _ := types.BaseType(c.SQLType)
	switch base {
	case "BOOLEAN", "BOOL":
		return "bool"
	case "SMALLINT", "INTEGER", "INT", "BIGINT":
		return "int"
	case "REAL", "DOUBLE PRECISION", "NUMERIC", "DECIMAL":
		return "float"
	case "TIMESTAMPTZ", "TIMESTAMP", "DATE", "TIME":
		return "datetime"
	case "JSON", "JSONB":
		return "json"
	case "BYTEA":
		return "bytes"
	default:
		return "string"
	}
}

func mermaidID(name string) string {
	id := safeIdent(name)
	if id == "" {
		return "Model"
	}
	return id
}

func safeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func escapeCell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}

func uniqueTables(tables []*schema.Table) []*schema.Table {
	seen := map[*schema.Table]bool{}
	var out []*schema.Table
	for _, t := range tables {
		if !seen[t] {
			seen[t] = true
			out = append(out, t)
		}
	}
	return out
}

func uniqueEnums(enums []*schema.Enum) []*schema.Enum {
	seen := map[*schema.Enum]bool{}
	var out []*schema.Enum
	for _, e := range enums {
		if !seen[e] {
			seen[e] = true
			out = append(out, e)
		}
	}
	return out
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
