-- Code generated by protoc-gen-protorm. DO NOT EDIT.
--
-- Database: {{.Database}}
-- Schema:   {{.Schema}}
{{- if .URL}}
-- Connection: {{.URL}}
{{- end}}

CREATE SCHEMA IF NOT EXISTS {{.Schema}};
{{range .Enums}}
-- {{.Comment}}
CREATE TYPE {{$.Schema}}.{{.SQLName}} AS ENUM ({{.ValueList}});
{{end}}
{{- range .Tables}}
{{- if .Comment}}
-- {{.Comment}}
{{- end}}
CREATE TABLE {{$.Schema}}.{{.Name}} (
{{- range .Items}}
{{- if .Comment}}
    -- {{.Comment}}
{{- end}}
    {{.Def}}{{if not .Last}},{{end}}
{{- end}}
);
{{range .Indexes}}{{.}}
{{end}}
{{- end}}