// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
// source: embedded.proto
//
// database: v1
// schema:   embedded_v1
//
// protorm — https://github.com/the-protobuf-project/protorm

package embeddedv1

import (
	"encoding/json"
	"time"
)

// Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.
type Event struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Repeated attendee resource names.
	Attendees []string `gorm:"column:attendees" json:"attendees,omitempty"`
	// Well-known type stays a scalar column, not a relation.
	CreateTime time.Time `gorm:"column:create_time;not null;autoCreateTime" json:"create_time"`
	// Map fields stay JSONB.
	Labels json.RawMessage `gorm:"column:labels" json:"labels,omitempty"`
	// Foreign key to Location.
	LocationID string    `gorm:"column:location_id;not null" json:"location_id" validate:"required"`
	Location   *Location `gorm:"foreignKey:LocationID;constraint:OnDelete:CASCADE" json:"location,omitempty"`
	// Foreign key to Location.
	BillingID *string   `gorm:"column:billing_id" json:"billing_id,omitempty"`
	Billing   *Location `gorm:"foreignKey:BillingID;constraint:OnDelete:SET NULL" json:"billing,omitempty"`
	// Foreign key to Metadata.
	MetadataID *string   `gorm:"column:metadata_id" json:"metadata_id,omitempty"`
	Metadata   *Metadata `gorm:"foreignKey:MetadataID;constraint:OnDelete:SET NULL" json:"metadata,omitempty"`
	// Back-relation: Attendee records that reference this via event_id.
	Attendees2 []Attendee `gorm:"foreignKey:EventID" json:"attendees2,omitempty"`
}

func (*Event) TableName() string { return "embedded_v1.events" }

// Attendee carries an IDENTIFIER, so that field is its primary key.
type Attendee struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Email address of the attendee.
	Email string `gorm:"column:email;not null" json:"email" validate:"required"`
	// Parent reference to Event (from the AIP resource pattern).
	EventID string `gorm:"column:event_id;not null" json:"event_id" validate:"required"`
	Event   *Event `gorm:"foreignKey:EventID;constraint:OnDelete:CASCADE" json:"event,omitempty"`
}

func (*Attendee) TableName() string { return "embedded_v1.attendees" }

// Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.
type Location struct {
	// Unique identifier for the location, assigned by the server.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// City where the location resides.
	City string `gorm:"column:city;not null" json:"city" validate:"required"`
	// Venue name within the city.
	Venue *string `gorm:"column:venue" json:"venue,omitempty"`
	// Back-relation: Event records that reference this via location_id.
	Events []Event `gorm:"foreignKey:LocationID" json:"events,omitempty"`
	// Back-relation: Event records that reference this via billing_id.
	Events2 []Event `gorm:"foreignKey:BillingID" json:"events2,omitempty"`
}

func (*Location) TableName() string { return "embedded_v1.locations" }

// Metadata is reachable only through Event.metadata and carries no resource annotation, yet it still becomes its own table (with a synthesized primary key) rather than an inlined JSONB blob.
type Metadata struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Free-form source system label.
	Source *string `gorm:"column:source" json:"source,omitempty"`
	// Arbitrary tags.
	Tags []string `gorm:"column:tags" json:"tags,omitempty"`
	// Back-relation: Event records that reference this via metadata_id.
	Events []Event `gorm:"foreignKey:MetadataID" json:"events,omitempty"`
}

func (*Metadata) TableName() string { return "embedded_v1.metadatas" }
